# Generated by Django 2.2.9 on 2020-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('tiffin_center_name', models.CharField(blank=True, max_length=300, verbose_name='Tiffin center name')),
                ('is_seller', models.BooleanField(default=False, verbose_name='is seller')),
                ('is_buyer', models.BooleanField(default=False, verbose_name='is buyer')),
                ('is_seller_approved', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserImages/')),
                ('food_type', models.CharField(choices=[('V', 'Veg'), ('N', 'Non-veg')], max_length=1)),
                ('pay', models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('O', 'Ontime')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
